metric: VOC
map_type: 11point
num_classes: 2

TrainDataset:
  !VOCDataSet
    #数据集所在文件夹
    dataset_dir: data/dataset
    #标注文件路径，相对 dataset_dir 路径，os.path.join(dataset_dir, anno_path)
    anno_path: train.txt
    #标签列表 [boat]
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    #数据集所在文件夹
    dataset_dir: data/dataset
    #标注文件路径，相对 dataset_dir 路径，os.path.join(dataset_dir, anno_path)
    anno_path: valid.txt
    #标签列表 [boat]
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: data/dataset/label_list.txt
